language: csharp
dist: xenial
mono: none
dotnet: 3.1
solution: RabbitSample.sln
branches:
  only:
    - master
    - dev
before_script:
  - chmod -R a+x scripts

script:
  - ./scripts/travis-build.sh

notifications:
  email:
    on_success: never
    on_failure: never